#!/usr/bin/env python3
"""
Generate a hemisphere (dome) OBJ mesh.
- Radius: 0.08 m
- Base flat at Z = 0 (equator)
- Apex at Z = +radius
- Outward-facing normals
"""

import math
import os

RADIUS = 0.08
STACKS = 16   # latitude divisions (0 = equator, STACKS = apex)
SLICES = 32   # longitude divisions

vertices = []
normals = []
faces = []

# Generate vertices row by row from equator (phi=0) to apex (phi=pi/2)
# phi: 0 (equator) -> pi/2 (apex)
for stack in range(STACKS + 1):
    phi = (math.pi / 2.0) * stack / STACKS   # 0..pi/2
    for slc in range(SLICES):
        theta = (2.0 * math.pi) * slc / SLICES
        x = RADIUS * math.cos(phi) * math.cos(theta)
        y = RADIUS * math.cos(phi) * math.sin(theta)
        z = RADIUS * math.sin(phi)
        vertices.append((x, y, z))
        # unit normal = same direction as vertex for a sphere
        normals.append((math.cos(phi) * math.cos(theta),
                        math.cos(phi) * math.sin(theta),
                        math.sin(phi)))

# Apex vertex (single point at top)
apex_idx = len(vertices) + 1  # OBJ is 1-indexed
vertices.append((0.0, 0.0, RADIUS))
normals.append((0.0, 0.0, 1.0))

# Base cap center vertex
base_center_idx = len(vertices) + 1
vertices.append((0.0, 0.0, 0.0))
normals.append((0.0, 0.0, -1.0))

# Also generate base-ring vertices with downward normals for the cap
# These are the same XY positions as stack=0 but with normal (0,0,-1)
base_ring_start = len(vertices) + 1
for slc in range(SLICES):
    theta = (2.0 * math.pi) * slc / SLICES
    x = RADIUS * math.cos(theta)
    y = RADIUS * math.sin(theta)
    vertices.append((x, y, 0.0))
    normals.append((0.0, 0.0, -1.0))

# ---- Helper: 1-indexed vertex index for (stack, slice) on the dome ----
def vidx(stack, slc):
    return stack * SLICES + (slc % SLICES) + 1  # 1-indexed

# ---- Dome quad/tri faces ----
# Between adjacent stacks: quads split into 2 triangles
for stack in range(STACKS - 1):
    for slc in range(SLICES):
        v0 = vidx(stack,     slc)
        v1 = vidx(stack,     slc + 1)
        v2 = vidx(stack + 1, slc + 1)
        v3 = vidx(stack + 1, slc)
        faces.append((v0, v1, v2))
        faces.append((v0, v2, v3))

# Top cap: triangles from last dome ring to apex
last_stack = STACKS - 1
for slc in range(SLICES):
    v0 = vidx(last_stack, slc)
    v1 = vidx(last_stack, slc + 1)
    faces.append((v0, v1, apex_idx))

# Bottom cap: fan from base_center to base ring (downward normal)
# Use base_ring vertices (separate vertices with Z-down normals)
for slc in range(SLICES):
    # Counter-clockwise when viewed from below (outward = downward)
    br0 = base_ring_start + slc
    br1 = base_ring_start + (slc + 1) % SLICES
    # CW from below = outward down normal
    faces.append((base_center_idx, br1, br0))

# ---- Write OBJ ----
out_path = os.path.join(os.path.dirname(__file__), "dome.obj")
with open(out_path, "w") as f:
    f.write("# Hemisphere dome mesh\n")
    f.write(f"# radius={RADIUS} m, stacks={STACKS}, slices={SLICES}\n")
    f.write("# Base flat at Z=0, apex at Z={:.4f}\n".format(RADIUS))
    f.write(f"# Generated by gen_dome.py\n\n")

    for (x, y, z) in vertices:
        f.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
    f.write("\n")
    for (nx, ny, nz) in normals:
        f.write(f"vn {nx:.6f} {ny:.6f} {nz:.6f}\n")
    f.write("\n")
    for tri in faces:
        a, b, c = tri
        f.write(f"f {a}//{a} {b}//{b} {c}//{c}\n")

print(f"Written: {out_path}")
print(f"  Vertices : {len(vertices)}")
print(f"  Faces    : {len(faces)}")
