controller_manager:
  ros__parameters:
    update_rate: 30

    spider_position_controller:
      type: "position_controllers/JointGroupPositionController"
      joints:
        - right_front_wheel_joint
        - right_back_wheel_joint
        - left_front_wheel_joint
        - left_back_wheel_joint

    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"

spider_position_controller:
  ros__parameters:
    gains:
      right_front_wheel_joint:
        p: 100.0
        i: 0.01
        d: 1.0
      right_back_wheel_joint:
        p: 100.0
        i: 0.01
        d: 1.0
      left_front_wheel_joint:
        p: 100.0
        i: 0.01
        d: 1.0
      left_back_wheel_joint:
        p: 100.0
        i: 0.01
        d: 1.0