controller_manager:
  ros__parameters:
    update_rate: 30 # Tasa de actualización en Hz
    
    # El controlador principal que usarás para la araña
    spider_position_controller:
      type: "position_controllers/JointGroupPositionController"
      joints: # Aquí se listarían las articulaciones de la araña (por ejemplo, 'hip_joint_1', 'femur_joint_1', etc.)
        - joint_rueda_prueba # Usamos la articulación de prueba por ahora
        
    # Publicador de estados de las articulaciones (Necesario para que Gazebo publique el estado)
    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"

spider_position_controller:
  ros__parameters:
    # Parámetros PID del controlador (se ajustan para un movimiento suave)
    # Estos son valores por defecto; ajústalos según la simulación.
    gains:
      joint_rueda_prueba:
        p: 100.0
        i: 0.01
        d: 1.0